### ISSUE TITLE
Uncaught Error: [DigiTrust Iframe Error] Client could not connect to the iframe

### ISSUE THREAD

**Issue by suhan0608** [digi-trust/dt-cdn#69]

**Comment by goosemanjack** [comment]
There was a real issue here. We have pushed a new release that should resolve the error. It may take a few hours for cache to expire and update for you. If you continue to see the error please provide a reference page where we can investigate further.

**Comment by tejasgajjar** [comment]
> There was a real issue here. We have pushed a new release that should resolve the error. It may take a few hours for cache to expire and update for you. If you continue to see the error please provide a reference page where we can investigate further.

Thanks for reply @goosemanjack .
Actually i am just trying to test it out in local.
Is this will work in the local env ?

**Comment by tejasgajjar** [comment]
> There was a real issue here. We have pushed a new release that should resolve the error. It may take a few hours for cache to expire and update for you. If you continue to see the error please provide a reference page where we can investigate further.

Thanks for the reply @goosemanjack.
Why i'm getting CORB issue when including the scritps in the site.?

**Comment by tejasgajjar** [comment]
Thanks for reply @goosemanjack .

Can you please help me for to check is this script is working or not in ad ? How can i check this ?

**Comment by goosemanjack** [comment]
You will need to set up a local environment. I'm assuming you have a
webserver as it will not work directly off the filesystem.

Check out dt-cdn\samples\sample01.html

This shows how you can pass settings to work off the local environment. In
this case the host file uses "local.digitru.st" to point to localhost.
Ideally you run SSL on your development webserver as that is also an issue
with Chrome.

**Comment by suhan0608** [comment]
@goosemanjack please check this URL http://qa.marketrealist.com/, if you see console it is currently giving me **Uncaught TypeError: Cannot read property 'id' of undefined** error.

What is the issue there i did not able to understand.

**Comment by goosemanjack** [comment]
This particular issue lies within your initialization callback. At line 733 you are reading from the result identity object before testing for the success case.

When success is false there is no identity present, so "console.log(digiTrustResult.identity.id)" throws an exception. Reverse these two lines as below and that particular error goes away.
```
console.log(digiTrustResult.success);
console.log(digiTrustResult.identity.id);
```
The page you reference works in both Firefox and Edge. It currently fails in Chrome due to the fact that Chrome does not expose the web crypto API when serving pages over a non-https connection. There is a fallback service to overcome, but it appears a configuration setting is currently disallowing the service from being called. I will update this thread more when I have more information.

**Comment by goosemanjack** [comment]
I have confirmed that the issue is specific to the Chrome browser over non-SSL connections. At this time we are unable to support the DigiTrust ID service on non-SSL content in the Chrome browser. This is due to a change made in Chrome 59 to remove support for the encryption operations we use on insecure origins. Our recommendation is to serve content over SSL.
